import type {
  FlashSaleSkuItem,
  SellerFlashSaleProductGroup,
  FlashSaleStatusResponse,
  CheckoutTicketResponse,
} from './flash-sale-types';

export const FIXTURE_FLASH_SALE_CAMPAIGN_ID = '00000000-0000-4000-8000-000000000999';

export const FIXTURE_SKUS: FlashSaleSkuItem[] = [
  {
    id: 'sku-fs-1',
    campaignId: FIXTURE_FLASH_SALE_CAMPAIGN_ID,
    productId: 'prod-1',
    variantId: 'var-1',
    variantName: 'Xanh dương / Size L',
    skuCode: 'SHIRT-BLUE-L',
    imageUrl: null,
    basePriceMinor: 250000,
    salePriceMinor: 150000,
    availablePhysical: 50,
    allocatedQuantity: 20,
    remainingQuantity: 12,
    netConsumedQuantity: 8,
    version: 1,
    state: 'ACTIVE',
    canEditQuota: false,
    canReplenish: false,
    canEnd: false,
  },
  {
    id: 'sku-fs-2',
    campaignId: FIXTURE_FLASH_SALE_CAMPAIGN_ID,
    productId: 'prod-1',
    variantId: 'var-2',
    variantName: 'Đỏ / Size M',
    skuCode: 'SHIRT-RED-M',
    imageUrl: null,
    basePriceMinor: 250000,
    salePriceMinor: 150000,
    availablePhysical: 30,
    allocatedQuantity: 15,
    remainingQuantity: 0,
    netConsumedQuantity: 15,
    version: 2,
    state: 'SOLD_OUT',
    canEditQuota: false,
    canReplenish: true,
    canEnd: true,
  },
  {
    id: 'sku-fs-3',
    campaignId: FIXTURE_FLASH_SALE_CAMPAIGN_ID,
    productId: 'prod-2',
    variantId: 'var-3',
    variantName: 'Tai nghe Bluetooth Đen',
    skuCode: 'AUDIO-BT-BLK',
    imageUrl: null,
    basePriceMinor: 500000,
    salePriceMinor: 299000,
    availablePhysical: 100,
    allocatedQuantity: 40,
    remainingQuantity: 40,
    netConsumedQuantity: 0,
    version: 1,
    state: 'UPCOMING',
    canEditQuota: true,
    canReplenish: false,
    canEnd: false,
  },
  {
    id: 'sku-fs-4',
    campaignId: FIXTURE_FLASH_SALE_CAMPAIGN_ID,
    productId: 'prod-3',
    variantId: 'var-4',
    variantName: 'Ốp lưng Chống sốc Trong suốt',
    skuCode: 'CASE-SHOCK-CLR',
    imageUrl: null,
    basePriceMinor: 80000,
    salePriceMinor: 49000,
    availablePhysical: 20,
    allocatedQuantity: 10,
    remainingQuantity: 0,
    netConsumedQuantity: 10,
    version: 3,
    state: 'ENDED',
    canEditQuota: false,
    canReplenish: false,
    canEnd: false,
    endedAt: '2026-09-07T12:00:00.000Z',
    endedReason: 'SELLER_TERMINATED',
  },
];

export const FIXTURE_SELLER_GROUPS: SellerFlashSaleProductGroup[] = [
  {
    productId: 'prod-1',
    productName: 'Áo thun thể thao nam thoáng khí cao cấp',
    productSlug: 'ao-thun-the-thao-nam',
    imageUrl: null,
    skus: [FIXTURE_SKUS[0]!, FIXTURE_SKUS[1]!],
  },
  {
    productId: 'prod-2',
    productName: 'Tai nghe không dây chống ồn',
    productSlug: 'tai-nghe-khong-day-chong-on',
    imageUrl: null,
    skus: [FIXTURE_SKUS[2]!],
  },
  {
    productId: 'prod-3',
    productName: 'Ốp lưng điện thoại chống sốc',
    productSlug: 'op-lung-chong-soc',
    imageUrl: null,
    skus: [FIXTURE_SKUS[3]!],
  },
];

export const FIXTURE_FLASH_SALE_STATUS: FlashSaleStatusResponse = {
  serverTime: new Date().toISOString(),
  startsAt: '2026-09-07T10:00:00.000Z',
  endsAt: '2026-09-07T22:00:00.000Z',
  items: [
    {
      variantId: 'var-1',
      state: 'ACTIVE',
      stateVersion: 1,
      salePriceMinor: 150000,
      canPurchase: true,
    },
    {
      variantId: 'var-2',
      state: 'SOLD_OUT',
      stateVersion: 2,
      salePriceMinor: 150000,
      canPurchase: false,
    },
    {
      variantId: 'var-3',
      state: 'UPCOMING',
      stateVersion: 1,
      salePriceMinor: 299000,
      canPurchase: false,
    },
    {
      variantId: 'var-4',
      state: 'ENDED',
      stateVersion: 3,
      salePriceMinor: null,
      canPurchase: false,
    },
  ],
};

export const FIXTURE_WAITING_TICKET: CheckoutTicketResponse = {
  ticketId: 'ticket-12345',
  status: 'WAITING',
  retryAfterSeconds: 5,
  message: 'Có nhiều người đang mua sắm. Bạn đang chờ đến lượt vào thanh toán.',
};

export const FIXTURE_ADMITTED_TICKET: CheckoutTicketResponse = {
  ticketId: 'ticket-12345',
  status: 'ADMITTED',
  retryAfterSeconds: 0,
  leaseExpiresAt: new Date(Date.now() + 120000).toISOString(),
  message: 'Đến lượt thanh toán. Đến lượt thanh toán không có nghĩa sản phẩm đã được giữ.',
};
