import { formatSellerPromotionVersionEtag, isSellerDiscountPage, isSellerDiscountSummary, isSellerVoucherDeleteResult, isSellerVoucherPage, isSellerVoucherSummary, type SellerDiscountCreateRequest, type SellerDiscountPage, type SellerDiscountSummary, type SellerDiscountUpdateRequest, type SellerPromotionAction, type SellerVoucherCreateRequest, type SellerVoucherDeleteResult, type SellerVoucherPage, type SellerVoucherSummary, type SellerVoucherUpdateRequest } from '@shopee-clone/contracts';
import { RoleApiError, type AuthenticatedFetcher } from './role-api';

const endpoint = (path: string) => new URL(path, process.env.NEXT_PUBLIC_API_BASE_URL ?? 'http://localhost:3001');
const readBody = async (response: Response): Promise<unknown> => { try { return await response.json(); } catch { return undefined; } };
const problemOf = (body: unknown) => { const value = body && typeof body === 'object' ? body as { detail?: unknown; invalidParameters?: unknown } : {}; return { detail: typeof value.detail === 'string' ? value.detail : undefined, invalidParameters: Array.isArray(value.invalidParameters) ? value.invalidParameters.filter((item): item is string => typeof item === 'string') : undefined }; };

async function request<T>(fetcher: AuthenticatedFetcher, url: URL, init: RequestInit, guard: (value: unknown) => value is T): Promise<{ value: T; etag: string | null }> {
  const response = await fetcher(url, { ...init, cache: 'no-store', headers: { Accept: 'application/json, application/problem+json', ...(init.body ? { 'Content-Type': 'application/json' } : {}), ...(init.headers ?? {}) } });
  const body = await readBody(response);
  if (!response.ok) throw new RoleApiError('status', response.status, problemOf(body));
  if (!guard(body)) throw new RoleApiError('contract', response.status);
  return { value: body, etag: response.headers.get('ETag') };
}

export const newPromotionIdempotencyKey = () => crypto.randomUUID();
export async function fetchSellerVouchers(fetcher: AuthenticatedFetcher, input: { state?: string; page?: number } = {}): Promise<SellerVoucherPage> { const url = endpoint('/api/v1/seller/promotions/vouchers'); Object.entries(input).forEach(([key, value]) => { if (value) url.searchParams.set(key, String(value)); }); return (await request(fetcher, url, { method: 'GET' }, isSellerVoucherPage)).value; }
export async function fetchSellerVoucher(fetcher: AuthenticatedFetcher, id: string): Promise<SellerVoucherSummary> { return (await request(fetcher, endpoint(`/api/v1/seller/promotions/vouchers/${encodeURIComponent(id)}`), { method: 'GET' }, isSellerVoucherSummary)).value; }
export async function createSellerVoucher(fetcher: AuthenticatedFetcher, input: SellerVoucherCreateRequest, idempotencyKey = newPromotionIdempotencyKey()): Promise<{ value: SellerVoucherSummary; etag: string | null }> { return request(fetcher, endpoint('/api/v1/seller/promotions/vouchers'), { method: 'POST', headers: { 'Idempotency-Key': idempotencyKey }, body: JSON.stringify(input) }, isSellerVoucherSummary); }
export async function updateSellerVoucher(fetcher: AuthenticatedFetcher, id: string, version: number, input: SellerVoucherUpdateRequest): Promise<{ value: SellerVoucherSummary; etag: string | null }> { return request(fetcher, endpoint(`/api/v1/seller/promotions/vouchers/${encodeURIComponent(id)}`), { method: 'PATCH', headers: { 'If-Match': formatSellerPromotionVersionEtag(version) }, body: JSON.stringify(input) }, isSellerVoucherSummary); }
export async function actionSellerVoucher(fetcher: AuthenticatedFetcher, id: string, version: number, action: SellerPromotionAction, idempotencyKey = newPromotionIdempotencyKey()): Promise<{ value: SellerVoucherSummary; etag: string | null }> { return request(fetcher, endpoint(`/api/v1/seller/promotions/vouchers/${encodeURIComponent(id)}/actions`), { method: 'POST', headers: { 'If-Match': formatSellerPromotionVersionEtag(version), 'Idempotency-Key': idempotencyKey }, body: JSON.stringify({ action }) }, isSellerVoucherSummary); }
export async function deleteSellerVoucher(fetcher: AuthenticatedFetcher, id: string, version: number): Promise<{ value: SellerVoucherDeleteResult; etag: string | null }> { return request(fetcher, endpoint(`/api/v1/seller/promotions/vouchers/${encodeURIComponent(id)}`), { method: 'DELETE', headers: { 'If-Match': formatSellerPromotionVersionEtag(version) } }, isSellerVoucherDeleteResult); }
export async function fetchSellerDiscounts(fetcher: AuthenticatedFetcher, input: { state?: string; page?: number } = {}): Promise<SellerDiscountPage> { const url = endpoint('/api/v1/seller/promotions/discounts'); Object.entries(input).forEach(([key, value]) => { if (value) url.searchParams.set(key, String(value)); }); return (await request(fetcher, url, { method: 'GET' }, isSellerDiscountPage)).value; }
export async function createSellerDiscount(fetcher: AuthenticatedFetcher, input: SellerDiscountCreateRequest, idempotencyKey = newPromotionIdempotencyKey()): Promise<{ value: SellerDiscountSummary; etag: string | null }> { return request(fetcher, endpoint('/api/v1/seller/promotions/discounts'), { method: 'POST', headers: { 'Idempotency-Key': idempotencyKey }, body: JSON.stringify(input) }, isSellerDiscountSummary); }
export async function updateSellerDiscount(fetcher: AuthenticatedFetcher, id: string, version: number, input: SellerDiscountUpdateRequest): Promise<{ value: SellerDiscountSummary; etag: string | null }> { return request(fetcher, endpoint(`/api/v1/seller/promotions/discounts/${encodeURIComponent(id)}`), { method: 'PATCH', headers: { 'If-Match': formatSellerPromotionVersionEtag(version) }, body: JSON.stringify(input) }, isSellerDiscountSummary); }
export async function actionSellerDiscount(fetcher: AuthenticatedFetcher, id: string, version: number, action: SellerPromotionAction, idempotencyKey = newPromotionIdempotencyKey()): Promise<{ value: SellerDiscountSummary; etag: string | null }> { return request(fetcher, endpoint(`/api/v1/seller/promotions/discounts/${encodeURIComponent(id)}/actions`), { method: 'POST', headers: { 'If-Match': formatSellerPromotionVersionEtag(version), 'Idempotency-Key': idempotencyKey }, body: JSON.stringify({ action }) }, isSellerDiscountSummary); }
