export const PRODUCT_SEARCH_PROJECTION_VERSION = 1;
export const PRODUCT_SEARCH_ANALYZER_VERSION = 1;
export const BUYER_SEARCH_PROFILE_FEATURE_SCHEMA_VERSION = 1;
export const PERSONALIZED_RANKING_MODEL_VERSION = 1;
export const PERSONALIZED_RANKING_SCRIPT_VERSION = 1;
